### ISSUE TITLE
PSN Tracking Stopped

### ISSUE THREAD

**Issue by PandaGaming4732** [WFCD/worldstate-emitter#219]
**Summary:**
Genesis bot stopped tracking fissures, invasions, arbitration, sorties, cetus, fortuna, necralisk, darvo, baro, nightwave, conclave and alerts for ps4/5 around 18:00 UTC on the 17th of march

---
**If issue, Reproduction:**
https://origin.ps4.warframe.com/dynamic/worldState.php

---
**Mockups, screenshots, evidence:**
N/A

**Comment by TobiTenno** [comment]
looks like DE fixed their stuff
